services:
  postgres:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD", "pg_isready", "-U", "ferdian" ]
#      interval: 5s
#      timeout: 5s
#      retries: 5

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # api to send data
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":9001"
#    healthcheck:
#      test: [ "CMD", "mc", "ready", "local" ]
#      interval: 5s
#      timeout: 5s
#      retries: 5

#  redis:
#    image: redis:7
#    ports:
#      - "6380:6379"
#    command: [ "redis-server" ]
##    healthcheck:
##      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
##      interval: 1s
##      timeout: 3s
##      retries: 5

  redis-node-1:
    image: redis:7
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6380:6379"
      - "16379:16379"
    volumes:
      - redis-data-1:/data
    networks:
      - redis-cluster-net

  redis-node-2:
    image: redis:7
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6381:6379"
      - "16380:16379"
    volumes:
      - redis-data-2:/data
    networks:
      - redis-cluster-net

  redis-node-3:
    image: redis:7
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6382:6379"
      - "16381:16379"
    volumes:
      - redis-data-3:/data
    networks:
      - redis-cluster-net

  redis-node-4:
    image: redis:7
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6383:6379"
      - "16382:16379"
    volumes:
      - redis-data-4:/data
    networks:
      - redis-cluster-net

  redis-node-5:
    image: redis:7
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6384:6379"
      - "16383:16379"
    volumes:
      - redis-data-5:/data
    networks:
      - redis-cluster-net

  redis-node-6:
    image: redis:7
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6385:6379"
      - "16384:16379"
    volumes:
      - redis-data-6:/data
    networks:
      - redis-cluster-net

volumes:
  postgres_data:
  redis-data-1:
  redis-data-2:
  redis-data-3:
  redis-data-4:
  redis-data-5:
  redis-data-6:

networks:
  redis-cluster-net: